Cloud-Computing-Project/gtest/gtest/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('places.urls')),
    url(r'^admin/', admin.site.urls),

]

Cloud-Computing-Project/gtest/places/urls.py
from django.conf.urls import url
from . import views

app_name = 'places'

urlpatterns = [
   # url(r'^home/$', views.home, name = 'home'),

    url(r'^register/$', views.adduser, name='register'),
    url(r'^$', views.logins, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^connection/$', views.formView, name='connection'),

    # /country_id/
    url(r'^(?P<country_id>[0-9]{1})$', views.city, name='city'),

    # country_id/city/
    url(r'^(?P<city_id>[0-9]{2})/[0-9]{2}$', views.place, name='place'),

    # country_id/city/attractions
    url(r'^[0-9]{2}/attractions/$', views.attraction, name='attraction'),

    url(r'^[0-9]{2}/booked/$', views.book, name='book')
    #country_id/city/attractions
    #url(r'^(?P<country_id>[0-9]+)/attraction/$', views.attraction, name = 'attraction')

    #country_id/city/attractions/place
    #url(r'^(?P<country_id>[0-9]+)/city/attractions/$', views.attraction, name='attraction')

]

Cloud-Computing-Project/gtest/places/models.py
from __future__ import unicode_literals
from django.db import models
#from django.core import urlresolvers


class User(models.Model):
    user_name = models.CharField(max_length=200)
    user_password = models.CharField(max_length=200)

    def __str__(self):
        return self.user_name

class Guide(models.Model):
    guide_name = models.CharField(max_length=200)
    guide_number = models.CharField(max_length=15)
    guide_places = models.CharField(max_length=500)

    def __str__(self):
        return self.guide_name

class Country(models.Model):
    country_name = models.CharField(max_length=200)

    def __str__(self):
        return self.country_name



class City(models.Model):
    city_name = models.CharField(max_length=200)
    country_id = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.city_name

Cloud-Computing-Project/gtest/places/forms.py
from django import forms

from django.contrib.auth.models import User

class LoginForm(forms.Form):
   username = forms.CharField(max_length = 100)
   password = forms.CharField(widget = forms.PasswordInput())


class CreateForm(forms.Form):
   username = forms.CharField(max_length = 100)
   email = forms.CharField(max_length= 100)
   password = forms.CharField(widget = forms.PasswordInput())

Cloud-Computing-Project/gtest/places/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import User, Guide, Country, City
import elasticsearch
import json
import requests
from requests_aws4auth import AWS4Auth
from googleplaces import GooglePlaces, types, lang
import boto3
from .forms import LoginForm, CreateForm
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import redirect



#from .forms import UserForm
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

def adduser(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)

            #print (new_user.password)
            login( request, new_user)
            username = new_user.username
            country = Country.objects.all()
            context = {'country': country, "username": username}
            return render(request, 'places/home.html', context)
    else:
        form = CreateForm()

    return render(request, 'places/adduser.html', {'form': form})

def logins(request):
    #
    #print ("in the view")

    if request.session.has_key('username'):
        username = request.session['username']
        country = Country.objects.all()
        context = {'country': country, "username": username}
        #return redirect('home', {"username": username})
        return render(request, 'places/home.html', context)
    else:
        username = "not logged in"
        if request.method == "POST":
            # Get the posted form
            MyLoginForm = LoginForm(request.POST)
            #print ("post is working")
            #form = UserForm(request.POST)

            if MyLoginForm.is_valid():
                #print "form is valid"
                username = MyLoginForm.cleaned_data['username']
                password = MyLoginForm.cleaned_data['password']
                user = authenticate(username=username, password=password)

                if user is not None:
                    #print "trying to login"
                    login(request, user)
                    request.session['username'] = username
                    #return redirect('home', {"username": username})
                    country = Country.objects.all()
                    context = {'country':country,"username": username}
                    return render(request, 'places/home.html', context)
                else:
                    #raise MyLoginForm.ValidationError("Sorry, that login was invalid. Please try again.")
                    MyLoginForm = LoginForm()
                    return HttpResponse("Invalid, please go back..")

        return render(request, 'places/login.html', {"username": username})


def formView(request):
   if request.session.has_key('username'):
      username = request.session['username']
      country = Country.objects.all()
      context = {'country': country, "username": username}
      #return redirect('home', {"username": username})
      return render(request, 'places/home.html', context)
   else:
      return render(request, 'places/login.html', {})

def logout(request):
   try:
      del request.session['username']
   except:
      pass
   return render(request, 'places/logout.html')

#
# def home(request):
#     country = Country.objects.all()
#     context = {'country':country}#,"username": username }
#     return render(request,'places/home.html',context)

def city(request, country_id):
    city = City.objects.filter(country_id = country_id)
#    country = Country.objects.all()

    context = {'cities':city,'country_id':country_id}# 'country': country}
    return render(request,'places/citi.html',context)

def place(request, city_id):
    city = City.objects.get(id = city_id)
    awslink = 'ENTER AWS ELASTIC SEARCH LINK ALONG WITH QUERY HERE'
    full = awslink + city.city_name
    tweet = requests.get(full)
    results = json.loads(tweet.text)
    round1 = results["hits"]["hits"]
    list1 = round1[0]['_source']['attractionslist']
    #attract = list1.split(',')
    context = {'list1':list1}
    return render(request,'places/attractions.html',context)

def attraction(request):
    sel = request.POST.getlist('attr[]')
    rank = []
    dest = Guide.objects.all()
    for i in dest:
    #    print (i,i.guide_places.split(','))
        list2=[]
    #print (dest)
    # spot = dest.guide_places.split(',')
    # for i in dest:
        spot = i.guide_places.split(',')
        count = 0
        for j in sel:
            for k in spot:
                if (k == j):
                    list2.append(k)
                    count += 1
        temp = {'Name': i.guide_name, 'matches': count, 'places':list2}
        rank.append(temp)
    newlist = sorted(rank, key=lambda k: k['matches'], reverse=True)
    context = {'newlist':newlist}
    return render(request,'places/select.html',context)

def book(request):
    # con = request.POST.get('book')
    # tet = request.POST.get('phone_number', False)
    # sns = boto3.client(service_name="sns",
    #                    aws_access_key_id='',
    #                    aws_secret_access_key='',
    #                    region_name='us-west-2')  # , use_ssl=True)
    # ph = Guide.objects.get(guide_name=con)
    # phone = ph.guide_number
    # number = tet
    # # days = request.POST.get('days')
    # # print(days)
    # Message_guide = "This is message to confirm that you have been booked and the user number is " + str(
    #     number) + " Please contact the number soon for furthur information"
    # Message_user = "This is a message to confirm that you have booked " + con + " as your guide and you will be contacted by the guide soon."
    # sns.publish(PhoneNumber=number, Message=Message_user)
    # sns.publish(PhoneNumber=phone, Message=Message_guide)
    # return render(request, 'places/book.html', {})


    con = request.POST.get('book')
    tet = request.POST.get('phone_number',False)
    ph = Guide.objects.get(guide_name=con)
    phone = ph.guide_number
    guideinfo = Guide.objects.all()
    #rds = boto3.setup_default_session(region_name='us-east-2')

    session = boto3.Session(
        aws_access_key_id='',
        aws_secret_access_key='',
        region_name='us-east-2',
    )
    # sqs = boto3.client(service_name="sqs",
    #                    aws_access_key_id='',
    #                    aws_secret_access_key='',
    #                    region_name='us-east-2')
    sqs = boto3.resource('sqs')
    #sqs = boto3.resource('sqs', region_name='us-east-2')
    queue = sqs.get_queue_by_name(QueueName='sms_test')
    #queue = sqs.create_queue(QueueName='sms_test')
    numbersqs = []
    numbersqs.append(tet)
    for i in numbersqs:
        queue.send_message(MessageBody=i)

    sns = boto3.client(service_name="sns",
                       aws_access_key_id='',
                       aws_secret_access_key='',
                       region_name='us-west-2')  # , use_ssl=True)

    queuesns = sqs.get_queue_by_name(QueueName='sms_test')
    for x in queuesns.receive_messages(VisibilityTimeout=1, MaxNumberOfMessages=10, WaitTimeSeconds=5):
        number = x.body
        print number
        for guide_n in guideinfo:

            print guide_n.guide_name
            if con == guide_n.guide_name:
                message_guide = "This is message to confirm that you have been booked and the user number is " + str(number) + " Please contact the number soon for furthur information"
                message_user = "This is a message to confirm that you have booked " + con + " as your guide and you will be contacted by the guide soon."
                sns.publish(PhoneNumber=phone, Message=message_guide)
                sns.publish(PhoneNumber=number, Message=message_user)
                print "done"
            else:
                print "Guide not found"
        return render(request, 'places/book.html', {})




    # ph = Guide.objects.get(guide_name = con)
    # phone = ph.guide_number
    # number = tet
    # Message_guide = "This is message to confirm that you have been booked and the user number is " + str(number) + " Please contact the number soon for furthur information"
    # Message_user = "This is a message to confirm that you have booked " + con + " as your guide and you will be contacted by the guide soon."
    # sns.publish(PhoneNumber=number, Message=Message_user)
    # sns.publish(PhoneNumber=phone, Message=Message_guide)
    # return render(request,'places/book.html',{})

Cloud-Computing-Project/gtest/places/templates/places/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'places:login'%}">Guider</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">


        </div>

    </div>
</nav>

      <form name = "form" action = ""
         method = "POST" >{% csrf_token %}

         <div style = "max-width:470px;">
            <center>
             <h4 class="h4">Sign Up</h4>
                </center>
            <center>
               <input type = "text" style = "margin-left:20%;"
                  placeholder = "username" name = "username" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>
               <input type = "password" style = "margin-left:20%;"
                  placeholder = "password" name = "password" />
            </center>
         </div>

          <br>

         <div style = "max-width:470px;">
            <center>
               <input type = "email" style = "margin-left:20%;"
                  placeholder = "email" name = "email" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>

               <button style = "border:0px; background-color:#4285F4; margin-top:8%;
                  height:35px; width:40%;margin-left:19%;" type = "submit"
                  value = "Login" >
                  <strong>Create Account</strong>
               </button>

            </center>
         </div>

      </form>

   </body>
</html>

Cloud-Computing-Project/gtest/places/templates/places/attractions.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'places:login'%}">Guider</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav pull-right">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'places:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a></li>
            </ul>
              <ul class="nav navbar-nav pull-right">
                  <li ><a href=""><span aria-hidden="true"></span><strong>&nbsp; {{username}}</strong></a></li>
            </ul>

        </div>

    </div>
</nav>
<ul>
    <form action="{% url 'places:attraction' %}" method="post">
    {% csrf_token %}
  <div class="container">
      <!-- Example row of columns -->

      <div class="row">
    {% for att in list1 %}
          <div class="col-md-6">
        <input type="checkbox" name="attr[]" value="{{ att }}"><label >{{ att }}</label> <br>
  </div>
        {% endfor %}
      </div>

      </div>
          <div class="container">
      <!-- Example row of columns -->

      <div class="row">
            <div class="container">
    <input type="submit" value="Suggest Guides" class="btn btn-primary">
                 </div>

      </div>

      </div>
    </form>
</ul>
</body>
</html>

Cloud-Computing-Project/gtest/places/templates/places/book.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Guider{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
.a {
    text-indent: 15px;
}
.b {
    text-indent: 25px;
}

input[type=text] {
    padding: 0;
    height: 30px;
    position: relative;
    left: 0;
    outline: none;
    border: 1px solid #cdcdcd;
    border-color: rgba(0,0,0,.15);
    background-color: white;
    font-size: 16px;
}
.advancedSearchTextbox {
    width: 526px;
    margin-right: -4px;
}
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'places:login'%}">Guider</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav pull-right">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'places:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a></li>
            </ul>


        </div>

    </div>
</nav>
        <p class="lead">Thanks for booking through Guider. You will be receiving a text message as a confirmation. Enjoy the trip</p>
</body>
</html>

Cloud-Computing-Project/gtest/places/templates/places/citi.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'places:login'%}">Guider</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav pull-right">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'places:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a></li>
            </ul>
              <ul class="nav navbar-nav pull-right">
                  <li ><a href=""><span aria-hidden="true"></span><strong>&nbsp; {{username}}</strong></a></li>
            </ul>

        </div>

    </div>
</nav>

<div class="container">
      <!-- Example row of columns -->

      <div class="row">
        {% for c in cities %}
        <div class="col-md-6">

          <h2>{{ c.city_name }}</h2>
          <p>Be an explorer and explore into the beautiful city of {{ c.city_name }}. See {{c.city_name}} like never before. Get ready for an adventure. Enjoy the culture, enjoy the trip, we are here to guide you.  </p>
          <p><a class="btn btn-primary" href="{% url 'places:place' c.id %}" role="button">Check Attractions &raquo;</a></p>

        </div>
        {% endfor %}
      </div>

      </div>
</body>
</html>

Cloud-Computing-Project/gtest/places/templates/places/home.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'places:login'%}">Guider</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav pull-right">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'places:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a></li>
            </ul>
              <ul class="nav navbar-nav pull-right">
                  <li ><a href=""><span aria-hidden="true"></span><strong>&nbsp;Hi {{username}}</strong></a></li>
            </ul>

        </div>

    </div>
</nav>
   {% block body %}
{% endblock %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Hello, Adventurer!</h1>
        <p>Welcome to the tourism website.
        	select the country you want to explore;
        </p>

      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->

      <div class="row">
        {% for count in country %}
        <div class="col-md-6">

          <h2>{{ count.country_name }}</h2>
          <p>Explore {{ count.country_name }}'s unique nature, wild life and exotic food. Get started on planning your holidays and learn more about yourself in this beautiful journey. Live in a city where something new awaits everyday. You are no more a stranger, we are here to guide you.</p>
          <p><a class="btn btn-primary" href="{% url 'places:city' count.id%}" role="button">Explore &raquo;</a></p>

        </div>
        {% endfor %}
      </div>

      </div>

</body>
</html>

Cloud-Computing-Project/gtest/places/templates/places/login.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

   <body>
   <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="#">Guider</a>
        </div>



    </div>
</nav>
   <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Hello, Adventurer!</h1>
        <p>Welcome to the tourism website.
        	select the country you want to explore;
        </p>

      </div>
    </div>
   <h5 style="margin-left:20%">Sign In</h5>




      <form name = "form" action = ""
         method = "POST" >{% csrf_token %}

         <div style = "max-width:470px;">
            <center>
               <input type = "text" style = "margin-left:20%;"
                  placeholder = "username" name = "username" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>
               <input type = "password" style = "margin-left:20%;"
                  placeholder = "password" name = "password" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>

               <button style = "border:0px; background-color:#4285F4; margin-top:1%;
                  height:35px; width:20%;margin-left:19%;" type = "submit"
                  value = "Login" >
                  <strong>Login</strong>
               </button>

            </center>
         </div>

      </form>

    <div>
        <h4>New User?</h4>
    <a href="{% url 'places:register' %}">Register here</a>
   </div>

   </body>
</html>

Cloud-Computing-Project/gtest/places/templates/places/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'places:login'%}">Guider</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">


        </div>

    </div>
</nav>
      You are logged out: <strong>{{username}}</strong>

     <div >
    <a class="btn btn-primary" href="{% url 'places:login' %}">Login</a>
   </div>
   </body>


</html>

Cloud-Computing-Project/gtest/places/templates/places/select.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
    <title>{% block title %}Guider{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
.a {
    text-indent: 15px;
}
.b {
    text-indent: 25px;
}

input[type=text] {
    padding: 0;
    height: 30px;
    position: relative;
    left: 0;
    outline: none;
    border: 1px solid #cdcdcd;
    border-color: rgba(0,0,0,.15);
    background-color: white;
    font-size: 16px;
}
.advancedSearchTextbox {
    width: 526px;
    margin-right: -4px;
}
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'places:login'%}">Guider</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav pull-right">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'places:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a></li>
            </ul>


        </div>

    </div>
</nav>
    <h2 class="lead">The best recommendations for the selected places are </h2>
    <form action = "{% url 'places:book' %}" method="post">
        {% csrf_token %}
     <ul>
         {% for i in newlist %}
         {% if i.matches != 0 %}
         <h4 >
             <input type="radio" name="book" value = "{{ i.Name }}">{{ i.Name }}
    </h4>

                 {% for j in i.places %}
          <div class="a">
                     <p>{{ j }}</p><br>
          </div>
             {% endfor %}


         {% endif %}
         {% endfor %}
     </ul>
        <div class="b">
        <input type="text" placeholder="Mobile number" name="phone_number"/>
        <input class="btn btn-primary" type="submit" value="Book Guide"/>
        </div>
        </form>
</body>
</html>